spring:
  cloud:
    gateway:
      #配置路由路径
      routes:
        - id: asfbbs-user-login
            uri: lb://asfbbs-user
            predicates:
              - Path=/asfbbs-user/user/login/**
            filters:
              - StripPrefix=1
              - ResponseModify=true
        - id: asfbbs-user
          uri: lb://asfbbs-user
          predicates:
            - Path=/asfbbs-user/**
          filters:
            - StripPrefix=1
        - id: asfbbs-auth
          uri: lb://asfbbs-auth
          predicates:
            - Path=/asfbbs-auth/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter  #限流filter
              args:
                keyResolver: '#{@ipAddressKeyResolver}' #对ip限流
                redis-rate-limiter.replenishRate: 1  # 令牌桶放入的速度
                redis-rate-limiter.burstCapacity: 1  # 令牌桶的容积
        - id: asfbbs-admin
          uri: lb://asfbbs-admin
          predicates:
            - Path=/asfbbs-admin/**
          filters:
            - StripPrefix=1
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/asfbbs-auth/rsa/publicKey' #配置RSA的公钥访问地址
#白名单路径配置
secure:
  ignore:
    urls:
      - "/doc/debug-all.html"
      - "/asfbbs-auth/oauth/token"
      - "/asfbbs-auth/oauth/authorize"
      - "/asfbbs-auth/rsa/publicKey"
      - "/asfbbs-admin/admin/login"