openapi: 3.0.3
info:
  title: 用户系统
  description: 用户基础信息及权限服务
  version: 1.0.0
servers:
  - url: 'https://api.asoulfan.com/user'
    description: '生产接口'
  - url: 'https://api-dev.asoulfan.com/user'
    description: '日常接口'
paths:
  /user/getUserInfo:
    get:
      security:
        - authorization: [ ]
      description: "获取用户信息"
      responses:
        200:
          description: "获取用户信息成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: "返回码"
                    enum:
                      - 200
                      - 401
                  message:
                    type: string
                    description: "返回信息"
                  data:
                    $ref: '#/components/schemas/userInfo'
  /permission/getUserPermission:
    get:
      security:
        - authorization: [ ]
      description: "获取用户权限"
      responses:
        200:
          description: "获取用户权限成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: "返回码"
                    enum:
                      - 200
                      - 401
                  message:
                    type: string
                    description: "返回信息"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/permission'
  /permission/auth:
    post:
      security:
        - authorization: [ ]
      description: "用户权限验证"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                permission:
                  type: string
                  description: "权限"
      responses:
        200:
          description: "用户权限验证成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: "返回码"
                    enum:
                      - 200
                      - 401
                  message:
                    type: string
                    description: "返回信息"
                  data:
                    type: boolean
                    description: "是否有权限"
components:
  securitySchemes:
    authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    userInfo:
      type: object
      description: "用户基本信息"
      properties:
        nickname:
          type: string
          description: "昵称"
        username:
          type: string
          description: "用户名"
        avatar:
          type: string
          description: "头像"
        email:
          type: string
          description: "邮箱"
        bUid:
          type: string
          description: "b站绑定uid"
        role:
          type: array
          description: "角色"
          items:
            $ref: '#/components/schemas/role'
        permission:
          type: array
          description: "权限"
          items:
            $ref: '#/components/schemas/permission'
    role:
      type: object
      description: "角色"
      properties:
        name:
          type: string
          description: "角色名"
        description:
          type: string
          description: "角色描述"
        permission:
          type: array
          description: "权限"
          items:
            $ref: '#/components/schemas/permission'
    permission:
      type: object
      description: "权限"
      properties:
        code:
          type: string
          description: "权限编码"
        name:
          type: string
          description: "权限名称"
        description:
          type: string
          description: "权限描述"
        url:
          type: string
          description: "权限url"





