server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      #配置路由路径
      routes:
        - id: asfbbs-auth
          uri: lb://asfbbs-auth
          predicates:
            - Path=/asfbbs-auth/**
          filters:
            - StripPrefix=1
        - id: asfbbs-admin
          uri: lb://asfbbs-admin
          predicates:
            - Path=/asfbbs-admin/**
          filters:
            - StripPrefix=1
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/asfbbs-auth/rsa/publicKey' #配置RSA的公钥访问地址
#白名单路径配置
secure:
  ignore:
    urls:
      - "/doc/debug-all.html"
      - "/asfbbs-auth/oauth/token"
      - "/asfbbs-auth/oauth/authorize"
      - "/asfbbs-auth/rsa/publicKey"
      - "/asfbbs-admin/admin/login"